<?php

/**
 * @file
 * Installation functions for Entity Translation module.
 */

/**
 * Implements hook_schema().
 */
function entity_translation_schema() {
  $schema = array();

  $schema['entity_translation'] = array(
    'description' => 'Table to track entity translations',
    'fields' => array(
      'entity_type' => array(
        'type' => 'varchar',
        'length' => 128,
        'not null' => TRUE,
        'default' => '',
        'description' => 'The entity type this translation relates to',
      ),
      'entity_id' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'description' => 'The entity id this translation relates to',
      ),
      'revision_id' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'description' => 'The entity revision id this translation relates to',
      ),
      'langcode' => array(
        'type' => 'varchar',
        'length' => 32,
        'not null' => TRUE,
        'default' => '',
        'description' => 'The target language for this translation.',
      ),
      'source' => array(
        'type' => 'varchar',
        'length' => 32,
        'not null' => TRUE,
        'default' => '',
        'description' => 'The source language from which this translation was created.',
      ),
      'uid' => array(
        'description' => 'The author of this translation.',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'status' => array(
        'description' => 'Boolean indicating whether the translation is published (visible to non-administrators).',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 1,
      ),
      'translate' => array(
        'description' => 'A boolean indicating whether this translation needs to be updated.',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'created' => array(
        'description' => 'The Unix timestamp when the translation was created.',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'changed' => array(
        'description' => 'The Unix timestamp when the translation was most recently saved.',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
    ),
    'primary key' => array('entity_type', 'entity_id', 'langcode'),
  );

  $schema['entity_translation_revision'] = array(
    'description' => 'Table to track entity translation revisions',
    'fields' => array(
      'entity_type' => array(
        'type' => 'varchar',
        'length' => 128,
        'not null' => TRUE,
        'default' => '',
        'description' => 'The entity type this translation revision relates to',
      ),
      'entity_id' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'description' => 'The entity id this translation revision relates to',
      ),
      'revision_id' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'description' => 'The entity revision id this translation relates to',
      ),
      'langcode' => array(
        'type' => 'varchar',
        'length' => 32,
        'not null' => TRUE,
        'default' => '',
        'description' => 'The target language for this translation revision.',
      ),
      'source' => array(
        'type' => 'varchar',
        'length' => 32,
        'not null' => TRUE,
        'default' => '',
        'description' => 'The source language from which this translation revision was created.',
      ),
      'uid' => array(
        'description' => 'The author of this translation revision.',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'status' => array(
        'description' => 'Boolean indicating whether the translation revision is published (visible to non-administrators).',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 1,
      ),
      'translate' => array(
        'description' => 'A boolean indicating whether this translation revision needs to be updated.',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'created' => array(
        'description' => 'The Unix timestamp when the translation revision was created.',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'changed' => array(
        'description' => 'The Unix timestamp when the translation revision was most recently saved.',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
    ),
    'primary key' => array('entity_type', 'revision_id', 'langcode'),
    'indexes'=> array('revision_id' => array('revision_id')),
  );

  return $schema;
}

/**
 * Implements hook_install().
 */
function entity_translation_install() {
  // entity_translation_form_alter() needs to run after locale_form_alter() and
  // translation_menu(); entity_translation_menu_alter() needs to run after
  // i18n_node_menu_alter().
  db_update('system')
    ->fields(array('weight' => 11))
    ->condition('name', 'entity_translation')
    ->execute();

  // Make translation use the content language type.
  $config = config('entity_translation.settings');
  $config->set('translation_language_type', LANGUAGE_TYPE_CONTENT);
  $config->save();
}

/**
 * Implements hook_enable().
 */
function entity_translation_enable() {
  // Re-activate entity translation for content types which had used it when
  // the module was last disabled (if any), unless these have since been altered
  // by the user to use a different translation option.
  $config = config('entity_translation.settings');
  $entity_translation_types = $config->get('entity_translation_disabled_content_types');
  if (is_array($entity_translation_types) && !empty($entity_translation_types)) {
    $config_data = $config->getData();
    $save_config = FALSE;
    foreach ($entity_translation_types as $index => $type) {
      $key = "language_content_type_$type";
      if (isset($config_data[$key]) && $config_data[$key] == 0) {
        $config->set("language_content_type_$type", ENTITY_TRANSLATION_ENABLED);
        $save_config = TRUE;
      }
      // We should show the warning only if we actually restored at least one
      // content type.
      else {
        unset($entity_translation_types[$index]);
      }
    }
    if ($save_config) {
      $config->save();
    }
    if (!empty($entity_translation_types)) {
      drupal_set_message(t('All content types previously configured to use field translation are now using it again.'), 'warning');
    }
    $config->clear('entity_translation_disabled_content_types');
    $config->save();
  }
}

/**
 * Implements hook_disable().
 */
function entity_translation_disable() {
  // Store record of which types are using entity translation, and set those
  // types to not be translated. These content types will be reset to use entity
  // translation again if the module is later re-enabled, unless they have been
  // changed by the user in the meantime.
  $entity_translation_types = array();
  $config = config('entity_translation.settings');
  $config_data = $config->getData();
  foreach (node_type_get_types() as $type => $object) {
    $key = "language_content_type_$type";
    if (isset($config_data[$key]) && $config_data[$key] == ENTITY_TRANSLATION_ENABLED) {
      $entity_translation_types[] = $type;
      $config->set("language_content_type_$type", 0);
    }
  }
  if ($entity_translation_types) {
    $config->set('entity_translation_disabled_content_types', $entity_translation_types);
    $config->save();
    drupal_set_message(t('All content types configured to use field translation now have multilingual support disabled. This change will be reverted if the entity translation module is enabled again.'), 'warning');
  }
}

/**
 * Implements hook_uninstall().
 */
function entity_translation_uninstall() {
  config('entity_translation.settings')->delete();
}

/**
 * Implements hook_update_last_removed().
 */
function entity_translation_update_last_removed() {
  return 7009;
}

/**
 * Backdrop migration
 */
function entity_translation_update_1000() {
  $config = config('entity_translation.settings');
  $config->set('entity_types', update_variable_get('entity_translation_entity_types', array('node' => 'node')));
  $config->set('translation_language_type', update_variable_get('translation_language_type', LANGUAGE_TYPE_CONTENT));
  $config->set('revision_enabled', update_variable_get('entity_translation_revision_enabled', TRUE));
  $config->set('taxonomy_autocomplete', update_variable_get('entity_translation_taxonomy_autocomplete', TRUE));
  $config->set('languages_enabled', update_variable_get('entity_translation_languages_enabled', FALSE));
  $config->set('locale_field_language_fallback', update_variable_get('locale_field_language_fallback', TRUE));
  $config->set('show_fallback_on_overview_pages', update_variable_get('entity_translation_show_fallback_on_overview_pages', FALSE));
  $config->set('shared_labels', update_variable_get('entity_translation_shared_labels', TRUE));
  $config->set('workflow_enabled', update_variable_get('entity_translation_workflow_enabled', FALSE));

  update_variable_del('entity_translation_entity_types');
  update_variable_del('translation_language_type');
  update_variable_del('entity_translation_revision_enabled');
  update_variable_del('entity_translation_taxonomy_autocomplete');
  update_variable_del('entity_translation_languages_enabled');
  update_variable_del('locale_field_language_fallback');
  update_variable_del('entity_translation_show_fallback_on_overview_pages');
  update_variable_del('entity_translation_shared_labels');
  update_variable_del('entity_translation_workflow_enabled');

  $language_query = "SHOW COLUMNS FROM {entity_translation} LIKE 'language';";
  $query = db_query($language_query);
  if ($query->rowCount()) {
    // update tables to use langcode instead of language
    $schema = entity_translation_schema();
    db_change_field('entity_translation', 'language', 'langcode', $schema['entity_translation']['langcode']);
    db_change_field('entity_translation_revision', 'language', 'langcode', $schema['entity_translation_revision']['langcode']);
  }

  $enabled_types = array_filter(update_variable_get('entity_translation_entity_types', array()));

  foreach ($enabled_types as $entity_type) {
    $entity_info = entity_get_info($entity_type);
    $label = !empty($entity_info['label']) ? $info['label'] : $entity_type;
    $bundles = array($entity_type => array('label' => $label));
    if (!empty($entity_info['bundles'])) {
      $bundles = $entity_info['bundles'];
    }

    foreach ($bundles as $bundle => $info) {
      $settings_key = 'entity_translation_settings_' . $entity_type . '__' . $bundle;
      $settings = update_variable_get($settings_key, array());
      if (!empty($settings)) {
        $config->set($entity_type . '__' . $bundle, $settings);
        update_variable_del($settings_key);
      }
    }
  }

  $config->save();
}
